const doSomething = () => {
  
  try {
   //code block
  } catch (err) {
    
    throw new Error(err.message)
  }
  
}